version: "2.4"
services:
  test2:
    build:
      context: .
      dockerfile: test2/Dockerfile
    depends_on:
      - postgres
    environment:
      TEST_CASE: TEST2
      SECRET: $SECRET
    volumes:
      - ./:/artefact
  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: dummyuser
      POSTGRES_PASSWORD: dummypassword
      POSTGRES_DB: dummydb
